stages:
  - build
  - deploy

.build_script:
  script: &build_script
    - docker login -u $REG_USER -p $REG_PASSWORD $REG_SERVER
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

.deploy_script:
  script: &deploy_script
    - envsubst < kube.yaml | kubectl --context=$CONTEXT apply -f -

build_beta:
  stage: build
  retry: 2
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
    REG_USER: gitlab-ci-token
    REG_PASSWORD: $CI_JOB_TOKEN
    REG_SERVER: $CI_REGISTRY
  script: *build_script
  only:
    - beta

build_master:
  stage: build
  retry: 2
  variables:
    REG_USER: $REGISTRY_USER
    REG_PASSWORD: $REGISTRY_PASSWORD
    REG_SERVER: $REGISTRY_SERVER
    IMAGE_TAG: $REGISTRY_SERVER/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
  script: *build_script
  only:
    - master

beta_deploy:
  stage: deploy
  retry: 2
  script: *deploy_script
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
    REG_USER: gitlab-ci-token
    REG_PASSWORD: $CI_JOB_TOKEN
    REG_SERVER: $CI_REGISTRY
    imagePullSecrets: regsecret
    CONTEXT: local
    REPLICAS: 1
  environment:
    name: beta
    url: http://pintapin.com
  only:
    - beta


production_deploy:
  stage: deploy
  retry: 2
  script: *deploy_script
  variables:
    REG_USER: $REGISTRY_USER
    REG_PASSWORD: $REGISTRY_PASSWORD
    REG_SERVER: $REGISTRY_SERVER
    IMAGE_TAG: $REGISTRY_SERVER/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
    imagePullSecrets: production-registry
    CONTEXT: pars
    REPLICAS: 1
  environment:
    name: production_parsonline
    url: http://pintapin.com
  only:
    - master


